services:
  app:
    env_file:
      - .env
    build:
      context: ./backend
      dockerfile: backend/docker/Dockerfile
      target: dev
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 3001:3001
    volumes:
      - ./backend:/app

  db:
    image: mariadb:lts
    restart: unless-stopped
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
      - MARIADB_AUTO_UPGRADE=yes
      - MARIADB_DATABASE=db
      - MARIADB_USER=db
      - MARIADB_PASSWORD=db
    volumes:
      - /var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping"]
      interval: 30s
      timeout: 2s
      retries: 5
      start_period: 5s
